services:
  # A Docker web service
  - type: web
    name: libritos
    runtime: docker
    repo: https://github.com/jd-apprentice/libritos.git
    region: oregon # optional (defaults to oregon)
    plan: starter # optional (defaults to starter instance type)
    branch: main # optional (defaults to master)
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /health