repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    files: ^cmd/.*\.go
    rev: v0.5.0
    hooks:
      - id: go-fmt
      # - id: go-imports      # TODO
      - id: no-go-testing
      # - id: golangci-lint   # TODO
      # - id: go-unit-tests   # TODO
